######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 30 14:56:37 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . Headers
INCLUDEPATH += . Headers

# Input
HEADERS += detec.h Headers/fftw3.h Headers/sndfile.h Headers/sndfile.hh
SOURCES += detec.cpp main.cpp
